[AUTH]
; Discord configuration
TOKEN_DISCORD =
DEFAULT_PREFIX =

[DDNET]
; DDNet map testing access point
TOKEN =
UPLOAD =
DELETE =

[DNSBL_API]
KEY =

[DATABASE]
; MariaDB access point
MARIADB_USER =
MARIADB_PASSWORD =
MARIADB_DB =
MARIADB_HOST =
MARIADB_PORT =

[TICKETS]
; Defines which role(s) get view/write permission to which ticket category
; Admin roles have access to everything on the server by default
; Leave VPN-BAN-APPEAL empty so only Admins (and the appellant) can see those tickets
REPORT =
BAN-APPEAL =
VPN-BAN-APPEAL =
RENAME =
ADMIN-MAIL =
COMPLAINT =

[WEATHER_API]
; Used in extensions/misc/misc.py to fetch Weather related data from https://api.openweathermap.org
KEY =