class _Guilds:
    DDNET = ...


Guilds = _Guilds()


class _Channels:
    CAT_INFORMATION = ...
    WELCOME = ...
    JOIN_LEAVE = ...
    ANNOUNCEMENTS = ...
    MAP_RELEASES = ...
    RECORDS = ...

    CAT_DEVELOPMENT = ...
    DEVELOPER = ...
    BUGS = ...

    CAT_DDRACENETWORK = ...
    GENERAL = ...
    SHOWROOM = ...
    QUESTIONS = ...
    WIKI = ...
    OFF_TOPIC = ...
    MAPPING = ...
    BOT_CMDS = ...

    CAT_TICKETS = ...
    TICKETS_INFO = ...
    TICKETS_TRANSCRIPTS = ...
    TH_REPORTS = ...
    TH_BAN_APPEALS = ...
    TH_RENAMES = ...
    TH_COMPLAINTS = ...
    TH_ADMIN_MAIL = ...

    CAT_SKIN_SUBM = ...
    SKIN_INFO = ...
    SKIN_SUBMIT = ...

    CAT_MODERATOR = ...
    MODERATOR = ...
    MODERATOR_LOUNGE = ...
    BANS = ...
    PLAYERFINDER = ...
    MATRIX_MOD = ...
    LOGS = ...

    CAT_INTERNAL = ...
    MOD_C = ...
    ADMIN = ...
    DBG = ...

    CAT_TESTING = ...
    TESTER_CHAT = ...
    TESTING_INFO = ...
    TESTING_SUBMIT = ...
    CAT_WAITING = ...
    CAT_EVALUATED = ...


Channels = _Channels()


class _Forums:
    MODERATOR_APPS = ...
    MODERATOR_ONBOARDING = ...
    TESTER_ONBOARDING = ...
    QUESTIONS = ...


Forums = _Forums()


class _ForumTags:
    SOLVED = ...


ForumTags = _ForumTags()


class _Roles:
    ADMIN = ...
    DISCORD_MODERATOR = ...
    MODERATOR = ...
    TESTER = ...
    TESTER_EXCL_TOURNAMENTS = ...
    TRIAL_TESTER = ...
    TRIAL_TESTER_EXCL_TOURNAMENTS = ...
    TESTING = ...
    SKIN_DB_CREW = ...
    WIKI_CONTRIBUTOR = ...
    DEV = ...
    TOURNAMENT_WINNER = ...


Roles = _Roles()


class _Emojis:
    DDNET = ...
    F3 = ...
    F4 = ...
    HAPPY = ...
    MMM = ...
    FLAG_UNK = ...
    CAMMOSTRIPES = ...
    BROWNBEAR = ...


Emojis = _Emojis()


class _Webhooks:
    DDNET_RECORDS = ...
    DDNET_MAP_RELEASES = ...


Webhooks = _Webhooks()


class _URLs:
    GITHUB_URL = "https://github.com/ddnet/ddnet-discordbot"


URLs = _URLs()
